source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
	gem "classifier-reborn"
	gem "jekyll-3rd-party-libraries"
	gem "jekyll-archives-v2"
	gem "jekyll-cache-bust"
	gem "jekyll-email-protect"
	gem "jekyll-feed"
	gem "jekyll-get-json"
	gem "jekyll-imagemagick"
	gem "jekyll-jupyter-notebook"
	gem "jekyll-link-attributes"
	gem "jekyll-minifier"
	gem "jekyll-paginate-v2"
	gem "jekyll-regex-replace"
	gem "jekyll-scholar"
	gem "jekyll-sitemap"
	gem "jekyll-socials"
	gem "jekyll-tabs"
	gem "jekyll-terser", git: "https://github.com/RobertoJBeltran/jekyll-terser.git"
	gem "jekyll-toc"
	gem "jekyll-twitter-plugin"
	gem "jemoji"
end

group :other_plugins do
	gem "css_parser"
	gem "observer"
	gem "ostruct"
end

group :al_folio_plugins do
	gem "al_folio_core", "= 1.0.15"
	gem "al_icons", "= 1.0.0"
	gem "al_folio_cv", "= 1.0.2"
	gem "al_folio_distill", "= 1.0.3"
	gem "al_folio_upgrade", "= 1.0.3"
	gem "al_folio_bootstrap_compat", "= 1.0.0"
	gem "al_cookie", "= 1.0.1"
	gem "al_analytics", "= 1.0.2"
	gem "al_citations", "= 1.0.1"
	gem "al_ext_posts", "= 1.0.3"
	gem "al_img_tools", "= 1.0.3"
	gem "al_search", "= 1.0.3"
	gem "al_charts", "= 1.0.1"
	gem "al_math", "= 1.0.2"
	gem "al_comments", "= 1.0.0"
	gem "al_newsletter", "= 1.0.0"
	gem "al_email_protect", "= 1.0.1"
	gem "al_marimo", "= 1.0.0"
	gem "al_rtl", "= 1.0.0"
end
